name: sqflite_database_example
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
   # database storage
  sqflite: ^2.3.0
   # format DateTime
  intl: ^0.18.1
   # display todos in grid
  flutter_staggered_grid_view: ^0.7.0
  path: ^1.8.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:

    - lib/components/assets/bg.png
    - lib/components/assets/bg1.JPG

 #    - images/a_dot_ham.jpeg


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Jost
      fonts:

        - asset: lib\components\fonts\Jost-Bold.ttf
        - asset: lib\components\fonts\Jost-Black.ttf
        - asset: lib\components\fonts\Jost-LightItalic.ttf
        - asset: lib\components\fonts\Jost-Light.ttf
